const GET_REGISTERED_USER = 'Auth/GET_REGISTERED_USER';
const GET_LOGGEDIN_USER = 'Auth/GET_LOGGEDIN_USER';
const SET_LOGGEDIN_USER = 'Auth/SET_LOGGEDIN_USER';


export{
    GET_REGISTERED_USER,
    GET_LOGGEDIN_USER,
    SET_LOGGEDIN_USER
};